server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///E:/Poli2024-1/PDS/Repos/Multiproject-config
  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}
